export type NominationField = 'company' | 'website' | 'description' | 'image' | 'ray' | 'offer' | 'create' | 'echo' | 'momentum' | 'legacy' | 'name' | 'email' | 'evidence' | 'nominee';
type Guidance = { title: string; introduction: string; steps: [string, string][]; note: string };
export const nominationGuidance: Record<NominationField, Guidance> = {
  company: { title: 'Company name', introduction: 'Make it clear which company you are nominating.', steps: [['Identify it', 'Use its official or commonly recognised name.'], ['Be specific', 'If the contribution belongs to a particular organisation within a group, name that organisation.']], note: 'Use the description to explain its work.' },
  nominee: { title: 'Who are you nominating?', introduction: 'Identify the person, company or project whose contribution you want the Institute to consider.', steps: [['Name them', 'Use the name people can recognise and verify.'], ['Keep the case for the nomination in the answers', 'Explain their contribution under the relevant principles below.']], note: 'You can nominate yourself or someone else.' },
  website: { title: 'Company website', introduction: 'Help reviewers find the company and check its work.', steps: [['Use an official source', 'Link to the company’s own website.'], ['Include the full address', 'Start the address with https:// or http://.']], note: 'A website supports the submission; the narrative should still stand on its own.' },
  description: { title: 'Short description', introduction: 'Give someone unfamiliar with the company a clear introduction before they read the five principles.', steps: [['What it does', 'Name the product, service or activity and who it serves.'], ['How it works', 'Explain the distinctive approach in concrete terms.'], ['Why it matters', 'Describe the difference that approach makes for people, resources or society.']], note: 'Aim for one or two focused paragraphs. Save the detailed case and evidence for the principles. Up to 3,000 characters.' },
  image: { title: 'Photo or logo', introduction: 'Choose an image that helps people recognise the company or understand its contribution.', steps: [['Show the work', 'A product, people at work or a place connected to the contribution can give useful context. A logo is also welcome.'], ['Check the image', 'Use a clear JPG, PNG or WebP up to 3 MB. A landscape image works well; keep the main subject away from the edges.']], note: 'Only upload an image you have permission to share. This field is optional.' },
  ray: { title: 'Ray of impact', introduction: 'Choose the main scale at which the contribution makes a difference.', steps: [['Find the beneficiaries', 'Is the strongest effect on an individual, a community, a team, a company, a country, the world or space?'], ['Match the evidence', 'Choose the scale your answers can substantiate. A company can have community impact; selling internationally does not by itself establish global impact.']], note: 'Choose the clearest fit. You can describe wider effects in your answers without overstating them.' },
  offer: { title: 'Offer · The contribution', introduction: 'Explain what the company gives, shares or makes possible for others.', steps: [['State the contribution', 'Open with the benefit that reaches beyond the transaction itself.'], ['Make it tangible', 'Describe what people can access, learn, use or experience because of the company’s work.'], ['Show its significance', 'Explain who benefits and why this contribution matters. Support it with a concrete practice, outcome or example.']], note: 'A useful offer can be knowledge, access, care or preservation as well as a product. Explain the contribution in your own words.' },
  create: { title: 'Create · Where new value comes from', introduction: 'Explain how resources go into creating value, and where that value relies less on guarding ownership, exclusivity or advantage.', steps: [['Name the starting point', 'Identify a resource, capability, idea or overlooked opportunity.'], ['Explain the transformation', 'Describe what the company does with it and what value emerges.'], ['Connect it to the principle', 'Show how the approach directs effort toward creation. Explain what can be recovered, understood or shared, and support the connection with an example.']], note: 'Be precise about the actual practice. Reuse or innovation alone is a starting point; explain why it expresses this principle.' },
  echo: { title: 'Echo · What changes in others', introduction: 'Look beyond the company’s own activity to its effect on other people’s thinking or behaviour.', steps: [['Name the assumption or habit', 'What do people normally believe, expect or do in this area?'], ['Describe the change', 'Explain how the company’s work influences what customers, peers or communities value, say or do.'], ['Ground the effect', 'Give an observed example, response or change in practice. If the effect is a possibility rather than an observed result, say so.']], note: 'Reach, followers and publicity can show exposure. Explain what changed because of that exposure.' },
  momentum: { title: 'Momentum · What existing assets set in motion', introduction: 'Show how the company activates what it already has to make something possible.', steps: [['Inventory the assets', 'Identify the space, tools, knowledge, relationships, materials or other resources already available.'], ['Describe how they are activated', 'Explain the decisions and actions that turn those assets into an opportunity.'], ['Show what follows', 'Describe the activities, capabilities or opportunities now supported by those resources, using a concrete example.']], note: 'Create explains the value being made. Momentum explains how available resources enable that work to move forward.' },
  legacy: { title: 'Legacy · What would be missing', introduction: 'Consider what remains beyond the immediate product, service or success of the business.', steps: [['Ask the disappearance question', 'If the company stopped tomorrow, what would people lose that another supplier could not readily replace?'], ['Name what endures', 'Identify knowledge, skills, relationships, culture, access or objects that can carry value into the future.'], ['Explain how it continues', 'Describe how that value is preserved, passed on or sustained. Distinguish what already exists from a future ambition.']], note: 'Make the lasting contribution specific. A company’s age or reputation alone does not explain its legacy.' },
  name: { title: 'Your name', introduction: 'Tell the Institute who is making this nomination.', steps: [['Identify yourself', 'Use the name you would like the Institute to use when contacting you.']], note: 'Your name stays private and does not appear in the public nomination gallery.' },
  email: { title: 'Your email', introduction: 'Give the Institute a contact address for questions about this submission.', steps: [['Use an address you check', 'Make sure the spelling is correct so the Institute can reach you if clarification is needed.']], note: 'Your email stays private and does not appear in the public nomination gallery.' },
  evidence: { title: 'Supporting link', introduction: 'Give reviewers a useful source for the contribution you describe.', steps: [['Choose a relevant source', 'Link to a project page, report, article or other material that directly supports your answers.'], ['Explain the case in the form', 'Include the important facts in your answers so a reviewer can understand the nomination before following the link.']], note: 'This field is optional. Distinguish independently documented facts from the company’s own claims.' },
};
export const arabicPrincipleGuidance: Partial<Record<NominationField, Guidance>> = {
  offer: { title: 'العطاء · OFFER', introduction: 'اشرح ما تقدمه الشركة أو تشاركه أو تتيحه للآخرين.', steps: [['حدد المساهمة', 'ابدأ بالفائدة التي تتجاوز عملية البيع نفسها.'], ['اجعلها ملموسة', 'صف ما يستطيع الناس تعلمه أو استخدامه أو الوصول إليه بفضل هذا العمل.'], ['وضح أهميتها', 'من المستفيد؟ ولماذا يهم هذا العطاء؟ قدم ممارسة أو نتيجة أو مثالاً محدداً.']], note: 'قد تكون المساهمة معرفة أو رعاية أو إتاحة فرصة أو حفظ شيء ذي قيمة. اشرحها بكلماتك.' },
  create: { title: 'الإبداع · CREATE', introduction: 'اشرح كيف تُوجَّه الموارد إلى خلق قيمة، وكيف تقل الحاجة إلى حماية الملكية أو الحصرية أو الميزة التنافسية.', steps: [['حدد نقطة البداية', 'سمِّ المورد أو القدرة أو الفكرة أو الفرصة التي لم تُستثمر.'], ['اشرح التحول', 'ماذا تفعل الشركة بهذا المورد؟ وما القيمة التي تنشأ؟'], ['اربطه بالمبدأ', 'وضح كيف يتجه الجهد نحو الإبداع وما يمكن استعادته أو فهمه أو مشاركته. قدم مثالاً يدعم ذلك.']], note: 'إعادة الاستخدام أو الابتكار نقطة بداية. اشرح تحديداً كيف تعبر الممارسة عن هذا المبدأ.' },
  echo: { title: 'الصدى · ECHO', introduction: 'صف تأثير العمل في تفكير الآخرين أو سلوكهم.', steps: [['حدد الاعتقاد أو العادة', 'ماذا يعتقد الناس عادةً أو يتوقعون أو يفعلون في هذا المجال؟'], ['صف التغيير', 'كيف يؤثر العمل فيما يقدره العملاء أو الزملاء أو المجتمع أو يقولونه أو يفعلونه؟'], ['قدم دليلاً', 'اذكر استجابة أو تغييراً لاحظته. إذا كان التأثير محتملاً فقط، وضح ذلك.']], note: 'الانتشار والمتابعون يظهرون وصول الرسالة. اشرح ما تغير بسببها.' },
  momentum: { title: 'الزخم · MOMENTUM', introduction: 'وضح كيف تستخدم الشركة ما لديها بالفعل لإتاحة شيء جديد.', steps: [['حدد الموارد المتاحة', 'سمِّ المساحات أو الأدوات أو المعرفة أو العلاقات أو المواد الموجودة.'], ['اشرح تفعيلها', 'ما القرارات والأفعال التي تحول هذه الموارد إلى فرصة؟'], ['صف ما ينتج عنها', 'اذكر الأنشطة أو القدرات أو الفرص التي أصبحت ممكنة، مع مثال محدد.']], note: 'الإبداع يشرح القيمة الجديدة. الزخم يشرح كيف تتيح الموارد المتاحة استمرار هذا العمل.' },
  legacy: { title: 'الإرث · LEGACY', introduction: 'تأمل ما يستمر بعد المنتج أو الخدمة أو النجاح المباشر.', steps: [['اطرح سؤال الغياب', 'لو توقفت الشركة غداً، ماذا سيُفقد مما لا يستطيع مورد آخر تعويضه بسهولة؟'], ['سمِّ ما يبقى', 'حدد المعرفة أو المهارات أو العلاقات أو الثقافة أو الأشياء التي تحمل قيمة للمستقبل.'], ['اشرح استمراره', 'كيف تُحفظ هذه القيمة أو تنتقل إلى الآخرين؟ ميز بين ما تحقق بالفعل والطموحات المستقبلية.']], note: 'حدد المساهمة الدائمة بدقة. عمر الشركة أو سمعتها وحدهما لا يفسران إرثها.' },
};
