// src/pages/awards/AssemblyPage.tsx
import { Link } from 'react-router-dom';
import AwardPageHero from '../../components/awards/AwardPageHero';
import { useLocale, type Locale } from '../../providers/LocaleProvider';

const COPY: Record<Locale,{eyebrow:string;title:string;intro:string;significance:string;p1:string;p2:string;host:string;hostCopy:string;button:string}> = {
  en:{eyebrow:'The Inaugural Assembly',title:'A room for the success the future deserves.',intro:'Seven Laureates, one Grand Laureate and the founding voices shaping a more beautiful definition of achievement.',significance:'Designed for significance, not scale.',p1:'The inaugural assembly is envisioned as an intimate global gathering of approximately 150 builders, jurors, nominators and institutional leaders.',p2:'Dubai is under exploration as the Founding Host City. No host partnership or venue will be announced before it is confirmed.',host:'Host the inaugural global assembly.',hostCopy:'We are opening conversations with institutions that can help establish an enduring home for Beautiful Success.',button:'Begin a host conversation'},
  de:{eyebrow:'Die Inaugural Assembly',title:'Ein Raum für den Erfolg, den die Zukunft verdient.',intro:'Sieben Laureates, ein Grand Laureate und Gründungsstimmen, die eine schönere Definition von Leistung prägen.',significance:'Für Bedeutung gestaltet, nicht für Größe.',p1:'Die erste Assembly ist als intime globale Zusammenkunft von rund 150 Gestaltern, Juroren, Nominierenden und institutionellen Führungspersönlichkeiten gedacht.',p2:'Dubai wird als Founding Host City geprüft. Keine Gastgeberpartnerschaft und kein Veranstaltungsort werden vor Bestätigung angekündigt.',host:'Die erste globale Assembly ausrichten.',hostCopy:'Wir öffnen Gespräche mit Institutionen, die Beautiful Success ein dauerhaftes Zuhause geben können.',button:'Gastgebergespräch beginnen'},
  fr:{eyebrow:'L’assemblée inaugurale',title:'Un lieu pour la réussite que l’avenir mérite.',intro:'Sept lauréats, un Grand Lauréat et des voix fondatrices qui façonnent une définition plus belle de la réussite.',significance:'Conçue pour la portée, pas pour la taille.',p1:'L’assemblée inaugurale est envisagée comme une rencontre mondiale intime d’environ 150 bâtisseurs, jurés, nominateurs et dirigeants institutionnels.',p2:'Dubaï est à l’étude comme ville hôte fondatrice. Aucun partenariat d’accueil ni lieu ne sera annoncé avant confirmation.',host:'Accueillir la première assemblée mondiale.',hostCopy:'Nous ouvrons des conversations avec des institutions capables d’aider à donner un foyer durable à Beautiful Success.',button:'Commencer une conversation d’accueil'},
  ar:{eyebrow:'الجمعية الافتتاحية',title:'مساحة للنجاح الذي يستحقه المستقبل.',intro:'سبعة فائزين وفائز كبير واحد وأصوات مؤسسة تصوغ تعريفاً أجمل للإنجاز.',significance:'مصممة للأهمية، لا للحجم.',p1:'نتصور الجمعية الافتتاحية لقاءً عالمياً حميمياً لنحو 150 من البنّائين والمحكمين والمرشحين والقادة المؤسسيين.',p2:'يجري استكشاف دبي كمدينة مضيفة مؤسسة. لن يتم الإعلان عن شراكة استضافة أو موقع قبل التأكيد.',host:'استضف الجمعية العالمية الافتتاحية.',hostCopy:'نفتح حوارات مع مؤسسات يمكنها المساعدة في إنشاء موطن دائم لـ Beautiful Success.',button:'ابدأ محادثة استضافة'},
  zh:{eyebrow:'首届大会',title:'为未来应得的成功，留出一个房间。',intro:'七位 Laureate、一位 Grand Laureate，以及共同塑造更美好成功定义的创始之声。',significance:'为意义而设计，而不是为规模。',p1:'首届大会设想为一场约 150 人的私密全球聚会，包括建设者、评委、提名者与机构领导者。',p2:'迪拜正在被考虑为创始主办城市。在正式确认之前，不会公布主办合作或场地。',host:'主办首届全球大会。',hostCopy:'我们正在与能够帮助 Beautiful Success 建立长期家园的机构展开对话。',button:'开启主办对话'},
  es:{eyebrow:'La Asamblea Inaugural',title:'Una sala para el éxito que merece el futuro.',intro:'Siete Laureados, un Gran Laureado y las voces fundadoras que dan forma a una definición más bella del logro.',significance:'Diseñada para la importancia, no para la escala.',p1:'La asamblea inaugural se concibe como un encuentro global íntimo de aproximadamente 150 creadores, jurados, nominadores y líderes institucionales.',p2:'Dubái está siendo explorada como Ciudad Anfitriona Fundadora. No se anunciará ninguna alianza anfitriona ni sede antes de su confirmación.',host:'Acoger la asamblea global inaugural.',hostCopy:'Estamos abriendo conversaciones con instituciones que puedan ayudar a establecer un hogar duradero para Beautiful Success.',button:'Iniciar una conversación como anfitrión'},
};

export default function AssemblyPage() {
  const { locale } = useLocale(); const copy = COPY[locale];
  return <main><AwardPageHero eyebrow={copy.eyebrow} title={copy.title}>{copy.intro}</AwardPageHero><section className="ibs-section award-copy-grid"><h2>{copy.significance}</h2><div><p>{copy.p1}</p><p>{copy.p2}</p></div></section><section className="ibs-section award-cta"><h2>{copy.host}</h2><p>{copy.hostCopy}</p><Link className="award-button" to="/contact?reason=Founding%20Host">{copy.button}</Link></section></main>;
}
